name: Android build apk for environment

on:
  push:
    branches: [ android-ci ]
  workflow_dispatch:
    inputs:
      part:
        description: 'Part of version to bump. Options: major, minor, patch'
        required: true
      dhiffieEnv:
        description: 'Name of the environment'
        required: true
      commitHash:
        description: 'Commit to make a build from'
        required: true

jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commitHash }}
          fetch-depth: '0'

      - run: ./.github/workflows/build-apk-input-validate.sh ${{ github.event.inputs.part }}

#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Build and Test
#        run: ./gradlew test
#
#      - name: Bump version and push tag
#        id: bump
#        uses: anothrNick/github-tag-action@v5.5
#        env:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          default_bump: ${{ github.event.inputs.part }}
#          tag_prefix: '${{ github.event.inputs.dhiffieEnv }}_'
