name: Android build apk for environment

on:
  workflow_dispatch:
    inputs:
      dhiffieEnv:
        description: 'Name of the environment'
        required: true
      branch:
        description: 'Branch to make a build from'
        required: true

jobs:
  test_bump_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    outputs:
      release_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: '0'

      - name: Set Version Tag
        run: echo "VERSION_TAG=$(./appVersion.sh ${{ github.event.inputs.dhiffieEnv }})" >> $GITHUB_ENV

      - name: Display Version
        run: echo $VERSION_TAG

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and Test
        run: ./gradlew test

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.VERSION_TAG }}
          RELEASE_BRANCHES: ${{ github.event.inputs.branch }}

  build_debug_apk:
    if: github.event.inputs.dhiffieEnv != 'prod'
    needs: test_bump_version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: '0'

      - name: Generate Base64 Signing Key
        run: echo "BASE_64_DEBUG=$(base64 -w 0 debug.jks)" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Release APK
        run: ./gradlew assembleDebug

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        with:
          releaseDirectory: Android/app/build/outputs/apk/debug
          signingKeyBase64: ${{ env.BASE_64_DEBUG }}
          alias: ""
          keyStorePassword: ""
          keyPassword: ""
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

#      - run: |
#          mkdir release
#          mv ${{ env.SIGNED_RELEASE_FILE }} release/app-release-signed.apk
#          cp app/build/outputs/mapping/release/mapping.txt release
#      - uses: actions/upload-artifact@v2
#        with:
#          name: release-apk
#          path: release

  build_release_apk:
    if: github.event.inputs.dhiffieEnv == 'prod'
    needs: test_bump_version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: '0'

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        with:
          releaseDirectory: Android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_JKS_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

#      - run: |
#          mkdir release
#          mv ${{ env.SIGNED_RELEASE_FILE }} release/app-release-signed.apk
#          cp app/build/outputs/mapping/release/mapping.txt release
#      - uses: actions/upload-artifact@v2
#        with:
#          name: release-apk
#          path: release

#  create_github_release:
#    needs: [build_release_apk]
#    runs-on: ubuntu-latest
#    steps:
#      - run: mkdir githubOutput
#
#      - uses: actions/download-artifact@v2
#        with:
#          name: release-apk
#          path: githubOutput
#
#      - uses: actions/download-artifact@v2
#        with:
#          name: release-bundle
#          path: githubOutput
#
#      - run: ls githubOutput
#
#      - name: Upload to GitHub Release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: githubOutput/*
#          tag: ${{ needs.bump_version.outputs.release_tag }}
#          file_glob: true
