name: Android build apk for environment

on:
  workflow_dispatch:
    inputs:
      part:
        description: 'Part of version to bump. Options: major, minor, patch'
        required: true
      dhiffieEnv:
        description: 'Name of the environment'
        required: true
      commitHash:
        description: 'Commit to make a build from'
        required: true

jobs:
  bump_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    outputs:
      release_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commitHash }}
          fetch-depth: '0'

      - name: Validate input
        run: ./../.github/workflows/build-apk-input-validate.sh ${{ github.event.inputs.part }}

      - name: Set Version Tag
        run: echo "VERSION_TAG=$(./appVersion.sh ${{ github.event.inputs.dhiffieEnv }})" >> $GITHUB_ENV

      - name: Display Version
        run: echo $VERSION_TAG

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and Test
        run: ./gradlew test

      - name: Bump version and push tag
        id: bump
        uses: mathieudutour/github-tag-action@v5.5
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.VERSION_TAG }}
